# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ShootX Virtual Try-On"
client_id = "{{CLIENT_ID}}"
application_url = "https://{{TUNNEL_URL}}"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_script_tags"

[auth]
redirect_urls = [
  "https://{{TUNNEL_URL}}/auth/callback",
  "https://{{TUNNEL_URL}}/auth/shopify/callback",
  "https://{{TUNNEL_URL}}/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "{{DEV_STORE_URL}}"
include_config_on_deploy = true